"use client";
import React from 'react';
import { motion } from 'framer-motion';
import { useInView } from 'framer-motion';
import { useRef } from 'react';

export default function AIEdgeInfrastructure() {
  const ref = useRef(null);
  const isInView = useInView(ref, { once: true });

  return (
    <section ref={ref} className="py-20 bg-gradient-to-br from-gray-50 to-blue-50 relative overflow-hidden">
      {/* Background Pattern */}
      <div className="absolute inset-0">
        <div className="absolute inset-0 bg-[url('data:image/svg+xml,%3Csvg%20width%3D%2260%22%20height%3D%2260%22%20viewBox%3D%220%200%2060%2060%22%20xmlns%3D%22http%3A//www.w3.org/2000/svg%22%3E%3Cg%20fill%3D%22none%22%20fill-rule%3D%22evenodd%22%3E%3Cg%20fill%3D%22%23f3f4f6%22%20fill-opacity%3D%220.3%22%3E%3Ccircle%20cx%3D%2230%22%20cy%3D%2230%22%20r%3D%222%22/%3E%3C/g%3E%3C/g%3E%3C/svg%3E')] opacity-20"></div>
      </div>

      <div className="container mx-auto px-4 relative z-10">
        {/* Main Heading */}
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={isInView ? { opacity: 1, y: 0 } : { opacity: 0, y: 30 }}
          transition={{ duration: 0.8 }}
          className="text-center mb-16"
        >
          <h2 className="text-3xl md:text-4xl font-bold text-blue-600 mb-6">
            AI-driven, Edge Infrastructure and Operational Intelligence
          </h2>
        </motion.div>

        <div className="grid grid-cols-1 lg:grid-cols-2 gap-12 items-center">
          {/* Left Side - Content */}
          <motion.div
            initial={{ opacity: 0, x: -50 }}
            animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: -50 }}
            transition={{ duration: 0.8, delay: 0.2 }}
          >
            <div className="bg-white rounded-2xl p-8 shadow-xl border border-gray-100">
              <h3 className="text-2xl font-bold text-gray-900 mb-6">
                Intelligent Operational Intelligence
              </h3>
              <p className="text-gray-600 leading-relaxed mb-4">
                Unlock the full potential of your edge infrastructure with ENPL's intelligent operational intelligence services. We leverage cutting-edge AI and machine learning to transform the data generated by your edge devices into actionable insights.
              </p>
              <p className="text-gray-600 leading-relaxed mb-4">
                These insights empower you to optimise performance, enhance security, and make data-driven decisions that improve operational efficiency. Our solutions provide real-time visibility into your edge environment, enabling you to proactively identify and address potential issues.
              </p>
              <p className="text-gray-600 leading-relaxed">
                We help you predict equipment failures, optimise energy consumption, and automate routine tasks. With our intelligent operational intelligence services, you can ensure the smooth and efficient operation of your edge infrastructure.
              </p>
            </div>
          </motion.div>

          {/* Right Side - Futuristic City Illustration */}
          <motion.div
            initial={{ opacity: 0, x: 50 }}
            animate={isInView ? { opacity: 1, x: 0 } : { opacity: 0, x: 50 }}
            transition={{ duration: 0.8, delay: 0.4 }}
            className="flex justify-center lg:justify-end"
          >
            <div className="relative">
              {/* Futuristic Cityscape */}
              <div className="bg-gray-900 rounded-2xl p-8 shadow-2xl">
                {/* City Buildings */}
                <div className="flex items-end justify-center space-x-2 mb-4">
                  <div className="w-8 h-16 bg-gray-700 rounded-t-lg border border-gray-500"></div>
                  <div className="w-6 h-20 bg-gray-600 rounded-t-lg border border-gray-400"></div>
                  <div className="w-10 h-24 bg-gray-800 rounded-t-lg border border-gray-600"></div>
                  <div className="w-7 h-18 bg-gray-700 rounded-t-lg border border-gray-500"></div>
                  <div className="w-9 h-22 bg-gray-600 rounded-t-lg border border-gray-400"></div>
                  <div className="w-5 h-14 bg-gray-800 rounded-t-lg border border-gray-600"></div>
                </div>

                {/* AI Cloud */}
                <div className="w-32 h-20 bg-pink-500 rounded-2xl mx-auto relative">
                  <div className="absolute inset-2 bg-pink-400 rounded-xl flex items-center justify-center">
                    <div className="text-white text-center">
                      <div className="text-sm font-bold">☁️</div>
                      <div className="text-xs mt-1">AI</div>
                    </div>
                  </div>
                  {/* Circuit Pattern */}
                  <div className="absolute inset-0 opacity-30">
                    <svg className="w-full h-full" viewBox="0 0 100 100">
                      <path d="M 20 20 L 40 20 L 40 40 L 60 40 L 60 60 L 80 60" stroke="white" strokeWidth="1" fill="none"/>
                      <circle cx="20" cy="20" r="2" fill="white"/>
                      <circle cx="40" cy="20" r="2" fill="white"/>
                      <circle cx="40" cy="40" r="2" fill="white"/>
                      <circle cx="60" cy="40" r="2" fill="white"/>
                      <circle cx="60" cy="60" r="2" fill="white"/>
                      <circle cx="80" cy="60" r="2" fill="white"/>
                    </svg>
                  </div>
                </div>

                {/* Connecting Network Lines */}
                <svg className="absolute inset-0 w-full h-full" viewBox="0 0 200 200">
                  <path d="M 50 80 Q 100 60 150 80" stroke="cyan" strokeWidth="2" fill="none" opacity="0.8"/>
                  <path d="M 50 100 Q 100 80 150 100" stroke="blue" strokeWidth="2" fill="none" opacity="0.8"/>
                  <path d="M 50 120 Q 100 100 150 120" stroke="purple" strokeWidth="2" fill="none" opacity="0.8"/>
                </svg>
              </div>
            </div>
          </motion.div>
        </div>
      </div>
    </section>
  );
}
